#!/usr/bin/env python3
"""
make_report.py
Generate a tabbed HTML report and a multi-page PDF from monitor output PNGs.

HTML: three tabs, linked PNGs by path (open in browser on cluster or copy
      plots dir to local machine).
PDF:  all plots as sequential pages, one per PNG.

Usage:
    python make_report.py --model TOM12_TJ_HA00
    python make_report.py --model TOM12_TJ_HA00 --year-start 1995 --year-end 2000
"""

import argparse
import glob
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
OUT_DIR_DEFAULT = Path(
    "/gpfs/home/mep22dku/scratch/NATL_MONITOR/plots"
)


def find_plot(plots_dir: Path, pattern: str) -> Path | None:
    matches = sorted(plots_dir.glob(pattern), key=lambda f: f.stat().st_mtime,
                     reverse=True)
    return matches[0] if matches else None


def collect_plots(model: str, plots_dir: Path,
                  year_start: int, year_end: int) -> dict:
    """Find all relevant PNGs in plots_dir (the report subfolder)."""
    def g(pattern):
        return find_plot(plots_dir, pattern)

    return {
        # Physical — maps use year_start/year_end; ts may differ (use glob)
        "phys_monitor":  g(f"{model}_na_monitor_*.png"),
        "phys_ts":       g(f"{model}_ts_physical_*.png"),
        # BGC
        "bgc_monitor":   g(f"{model}_bgc_monitor_annual_*.png"),
        "bgc_ts":        g(f"{model}_ts_bgc_*.png"),
        # Ecosystem
        "eco_monitor":   g(f"{model}_eco_monitor_*.png"),
    }


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Helvetica Neue', Arial, sans-serif;
          background: #f5f5f5; color: #1a1a1a; }}
  header {{ background: #1a1a1a; color: #f5f5f5; padding: 18px 32px; }}
  header h1 {{ font-size: 1.3em; font-weight: 500; letter-spacing: 0.03em; }}
  header p  {{ font-size: 0.85em; color: #aaa; margin-top: 4px; }}

  .tab-bar {{ display: flex; background: #2d2d2d; padding: 0 32px; }}
  .tab-bar button {{
    background: none; border: none; color: #bbb;
    padding: 12px 22px; font-size: 0.95em; cursor: pointer;
    border-bottom: 3px solid transparent; transition: all 0.15s;
  }}
  .tab-bar button:hover  {{ color: #fff; }}
  .tab-bar button.active {{ color: #fff; border-bottom-color: #4477AA; }}

  .tab-content {{ display: none; padding: 28px 32px; }}
  .tab-content.active {{ display: block; }}

  .plot-grid {{ display: grid; gap: 24px; }}
  .plot-grid.cols-1 {{ grid-template-columns: 1fr; }}
  .plot-grid.cols-2 {{ grid-template-columns: 1fr 1fr; }}

  .plot-card {{
    background: #fff; border-radius: 6px;
    box-shadow: 0 1px 4px rgba(0,0,0,0.10); overflow: hidden;
  }}
  .plot-card h2 {{
    font-size: 0.85em; font-weight: 500; letter-spacing: 0.04em;
    text-transform: uppercase; color: #666;
    padding: 10px 16px; border-bottom: 1px solid #eee;
  }}
  .plot-card img {{
    width: 100%; height: auto; display: block;
  }}
  .plot-card .missing {{
    padding: 40px; text-align: center; color: #aaa; font-size: 0.9em;
  }}

  footer {{
    text-align: center; font-size: 0.75em; color: #aaa;
    padding: 20px; border-top: 1px solid #ddd; margin-top: 12px;
  }}
</style>
</head>
<body>

<header>
  <h1>{title}</h1>
  <p>{subtitle}</p>
</header>

<div class="tab-bar">
  <button class="active" onclick="showTab(event,'tab-physical')">Physical</button>
  <button onclick="showTab(event,'tab-bgc')">BGC &amp; Ecosystem</button>
  <button onclick="showTab(event,'tab-eco-ts')">Ecosystem timeseries</button>
</div>

<!-- Tab 1: Physical -->
<div id="tab-physical" class="tab-content active">
  <div class="plot-grid cols-1">
    {phys_monitor_card}
    {phys_ts_card}
  </div>
</div>

<!-- Tab 2: BGC & Ecosystem maps -->
<div id="tab-bgc" class="tab-content">
  <div class="plot-grid cols-1">
    {bgc_monitor_card}
    {eco_monitor_card}
  </div>
</div>

<!-- Tab 3: Ecosystem timeseries -->
<div id="tab-eco-ts" class="tab-content">
  <div class="plot-grid cols-1">
    {bgc_ts_card}
  </div>
</div>

<footer>
  Generated by make_report.py &nbsp;·&nbsp; {model} &nbsp;·&nbsp; {year_start}–{year_end}
</footer>

<script>
function showTab(evt, tabId) {{
  document.querySelectorAll('.tab-content').forEach(t => t.classList.remove('active'));
  document.querySelectorAll('.tab-bar button').forEach(b => b.classList.remove('active'));
  document.getElementById(tabId).classList.add('active');
  evt.currentTarget.classList.add('active');
}}
</script>
</body>
</html>
"""


def img_card(title: str, fpath, plots_dir: Path) -> str:
    if fpath is None or not Path(fpath).exists():
        return f'<div class="plot-card"><h2>{title}</h2><div class="missing">Plot not found</div></div>'
    # Use filename only — HTML lives in the same directory as the plots
    rel = Path(fpath).name
    return (f'<div class="plot-card"><h2>{title}</h2>'
            f'<img src="./{rel}" alt="{title}"></div>')


def make_html(model: str, year_start: int, year_end: int,
              plots: dict, out_path: Path, plots_dir: Path):
    html = HTML_TEMPLATE.format(
        title=f"NA Monitor — {model} — {year_start}–{year_end}",
        subtitle=f"North Atlantic diagnostic monitor suite  ·  years {year_start}–{year_end}",
        model=model,
        year_start=year_start,
        year_end=year_end,
        phys_monitor_card=img_card("Physical monitor (maps)",   plots["phys_monitor"], plots_dir),
        phys_ts_card=     img_card("Physical timeseries",       plots["phys_ts"],      plots_dir),
        bgc_monitor_card= img_card("BGC monitor (maps)",        plots["bgc_monitor"],  plots_dir),
        eco_monitor_card= img_card("Ecosystem monitor (maps)",  plots["eco_monitor"],  plots_dir),
        bgc_ts_card=      img_card("BGC & plankton timeseries", plots["bgc_ts"],       plots_dir),
    )
    out_path.write_text(html)
    print(f"  HTML written: {out_path}")


# ---------------------------------------------------------------------------
# PDF
# ---------------------------------------------------------------------------

def make_pdf(model: str, year_start: int, year_end: int,
             plots: dict, out_path: Path):
    import matplotlib.pyplot as plt
    from matplotlib.backends.backend_pdf import PdfPages
    from matplotlib.image import imread

    # Ordered pages with titles
    pages = [
        ("Physical monitor (maps)",   plots["phys_monitor"]),
        ("Physical timeseries",       plots["phys_ts"]),
        ("BGC monitor (maps)",        plots["bgc_monitor"]),
        ("BGC & plankton timeseries", plots["bgc_ts"]),
        ("Ecosystem monitor (maps)",  plots["eco_monitor"]),
    ]

    with PdfPages(out_path) as pdf:
        # Cover page
        fig = plt.figure(figsize=(11.7, 8.3))   # A4 landscape
        fig.patch.set_facecolor("#1a1a1a")
        fig.text(0.5, 0.55, f"NA Monitor Suite",
                 ha="center", va="center", fontsize=28,
                 color="#f5f5f5", fontweight="light")
        fig.text(0.5, 0.45, f"{model}  ·  {year_start}–{year_end}",
                 ha="center", va="center", fontsize=18, color="#aaaaaa")
        fig.text(0.5, 0.35, "North Atlantic diagnostic monitor",
                 ha="center", va="center", fontsize=12, color="#666666")
        pdf.savefig(fig, facecolor=fig.get_facecolor())
        plt.close(fig)

        for title, fpath in pages:
            if fpath is None or not Path(fpath).exists():
                print(f"  WARNING: {title} — file not found, skipping page.")
                continue
            img = imread(str(fpath))
            # Scale to A4 landscape
            h, w = img.shape[:2]
            fig_w, fig_h = 11.7, 8.3
            aspect = w / h
            if aspect > fig_w / fig_h:
                img_w, img_h = fig_w - 0.4, (fig_w - 0.4) / aspect
            else:
                img_h, img_w = fig_h - 0.8, (fig_h - 0.8) * aspect

            fig = plt.figure(figsize=(fig_w, fig_h))
            fig.patch.set_facecolor("white")
            # Title strip
            fig.text(0.5, 0.97, title, ha="center", va="top",
                     fontsize=10, color="#444444")
            fig.text(0.5, 0.93, f"{model}  ·  {year_start}–{year_end}",
                     ha="center", va="top", fontsize=8, color="#aaaaaa")
            ax = fig.add_axes([
                (fig_w - img_w) / 2 / fig_w,
                (fig_h - img_h) / 2 / fig_h - 0.03,
                img_w / fig_w,
                img_h / fig_h,
            ])
            ax.imshow(img)
            ax.axis("off")
            pdf.savefig(fig, facecolor="white")
            plt.close(fig)
            print(f"  PDF page: {title}")

    print(f"  PDF written: {out_path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--model",      required=True)
    parser.add_argument("--year-start", type=int, default=None)
    parser.add_argument("--year-end",   type=int, default=None)
    parser.add_argument("--plots-dir",  type=Path, default=OUT_DIR_DEFAULT)
    parser.add_argument("--out-dir",    type=Path, default=None,
                        help="Output dir for HTML/PDF (default: same as plots-dir)")
    parser.add_argument("--skip-html",  action="store_true")
    parser.add_argument("--skip-pdf",   action="store_true")
    args = parser.parse_args()

    out_dir = args.out_dir or args.plots_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    # Auto-detect year range from available timeseries PNGs if not given
    if args.year_start is None or args.year_end is None:
        ts_files = sorted(args.plots_dir.glob(f"{args.model}_ts_physical_*.png"))
        if ts_files:
            m = re.search(r"_(\d{4})_(\d{4})\.png$", ts_files[-1].name)
            if m:
                args.year_start = args.year_start or int(m.group(1))
                args.year_end   = args.year_end   or int(m.group(2))
    if args.year_start is None or args.year_end is None:
        print("ERROR: could not auto-detect year range. Pass --year-start and --year-end.")
        sys.exit(1)

    print(f"\nCollecting plots for {args.model} {args.year_start}–{args.year_end}…")
    print(f"  Searching in: {args.plots_dir}")
    print(f"  PNGs found: {[f.name for f in sorted(args.plots_dir.glob('*.png'))]}")
    plots = collect_plots(args.model, args.plots_dir, args.year_start, args.year_end)
    for k, v in plots.items():
        print(f"  {k}: {v.name if v else 'NOT FOUND'}")

    yr = f"{args.year_start}_{args.year_end}"

    if not args.skip_html:
        make_html(args.model, args.year_start, args.year_end, plots,
                  out_path=out_dir / f"{args.model}_monitor_{yr}.html",
                  plots_dir=args.plots_dir)

    if not args.skip_pdf:
        make_pdf(args.model, args.year_start, args.year_end, plots,
                 out_path=out_dir / f"{args.model}_monitor_{yr}.pdf")

    print("\nDone.")


if __name__ == "__main__":
    main()
